import type { Metadata } from "next";
import "./globals.css";
// import MovieLogo from "@/icons/MovieLogo";
// import { Button } from "@/components/ui/button";
import Header from "@/components/my-component/Headerr";
import Footer from "@/components/my-component/Footer";
import { ThemeProvider } from "@/components/my-component/ThemeProvider";

export const metadata: Metadata = {
  title: "Shoyo's movie guide",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
